apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodexporter-rolebind
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
  namespace: default
roleRef:
  kind: Role
  name: nodeexporter-role
  apiGroup: rbac.authorization.k8s.io