version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      TZ: "Asia/Kolkata"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - /opt/grafana/grafana:/var/lib/grafana
    ports:
      - 3000:3000