global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'http_sd_configs'
    http_sd_configs:
    - url: http://nginx/http_sd.json
