pipeline{
    agent{
        label "worker1"
    }
    options{
        timestamps()
        timeout(time: 30, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }
  
    stages{
        stage("checkov-scan"){
            steps{
                dir("kubernetes/keycloak"){
                sh '''
                #static analyisi of Deployment
                docker run -t -v $(pwd):/output bridgecrew/checkov -f /output/keycloak-deploy.yml -o json |  jq '.' > k8deploy_result | exit 0
                docker run -t -v $(pwd):/output bridgecrew/checkov -f /output/keycloak-postgres.yml -o json |  jq '.' >> k8deploy_result | exit 0
                cat k8deploy_result | grep -B 4 'result'
                '''
                }
            }
        }
        stage("deploy"){
            steps{
                dir("kubernetes/keycloak"){
                sh '''
                #use sed command to replace the creds or use k8 secret

                kubectl apply -f keycloak-deploy.yml -n keycloak
                kubectl apply -f keycloak-postgres.yml -n keycloak
                '''
                }
            }    
        }
    }
}
