apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: "In"
                values:
                - arm64
      tolerations:
      - key: "key"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: keycloak
        #image: quay.io/keycloak/keycloak
        image: koolwithk/keycloak-arm:16.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
          limits:
            memory: 1024Mi
            cpu: 2000m
        env:
        - name: DB_VENDOR
          value: POSTGRES
        - name: DB_ADDR
          value: keycloak-postgres-svc
        - name: DB_DATABASE
          value: keycloak_db
        - name: DB_USER
          value: keycloak_user
        - name: DB_SCHEMA
          value: public
        - name: DB_PASSWORD
          value: postgres
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: PROXY_ADDRESS_FORWARDING
          value: true
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
spec:
  selector:
    app: keycloak
  type: NodePort
  ports:
  - name: keycloak-svc
    port: 8080
    targetPort: 8080
    nodePort: 30021
