apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    weekend-costsaving: true
spec:
  selector:
    matchLabels:
      app: nginx-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx-deploy
        image: nginx