---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "dev"
  name: scale-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scale-clusterrole
rules:
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   verbs:
#   - get
#   - list
#   - watch
#   - create
#   - update
#   - patch
#   - delete
- apiGroups:
  - "apps"
  resources:
  - deployments
  - deployments/scale
  verbs:
  # - get
  # - list
  # - watch
  # - create
  # - update
  - patch
  # - delete

---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: "dev"
#   name: scale-role
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   verbs:
#   - get
#   - list
#   - watch
#   - create
#   - update
#   - patch
#   - delete
# - apiGroups:
#   - "apps"
#   resources:
#   - deployments
#   - deployments/scale
#   verbs:
  # - get
  # - list
  # - watch
  # - create
  # - update
  # - patch
  # - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scale-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scale-clusterrole
subjects:
  - kind: ServiceAccount
    name: scale-sa
    namespace: "dev"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "dev"
  name: scale-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scale-role
subjects:
  - kind: ServiceAccount
    name: scale-sa